### ISSUE TITLE
What does the variable conflict and in_conflict used for?

### ISSUE THREAD

**Issue by godjoem** [jkoppel/sat#1]

**Comment by jkoppel** [comment]
Wow! This was quite a shock to receive. This is a class project from 8 years ago.

Those sets are used for conflict-directed backjumping. They're used to track the variables involved in the contradiction encountered in one branch of the seacrh.

https://en.wikipedia.org/wiki/Backjumping#Conflict-based_backjumping_(aka_conflict-directed_backjumping_(cbj))

**Comment by tcw123** [comment]
Could you describe it in detail?

**Comment by godjoem** [comment]
Thank you Sir. I have one more question, I don't quite understand the way you handle the variables `npos_app` and `nneg_app` because of the lack of comments. Such like that in function assign:
```
            if(sign < 0)
                nneg_app[v]--;
            else
                npos_app[v]++;
```

How do you handle these two variables，and do you used the VSIDS policy?

（If you add some more comments to your code, it will help me understand.）

**Comment by jkoppel** [comment]
Dude....these are some heavy questions for an 8 year-old homework assignment. Can you explain your interest in this codebase?

Those two arrays store the number of negative and positive appearances of each variable in outstanding clauses.

I don't know what VSIDS is, so probably not.
